### PR TITLE
Update _advanced.md

### PR DESCRIPTION
**Pull request by wernight**
Describe simpler terminal GUI option.

### CODE REVIEW

**Comment by nyboer** [comment]
I'm going to leave it as it for now for consistency.

**Comment by wernight** [comment]
Consistency with? Sorry I don't understand why suggesting to use `nmtui` which is a lot simpler, is inconsistent with the rest of the documentation. May be I can just update my PR?

**Comment by wernight** [comment]
Please give an update on the PR. I spent time to provide them in hope that it helps CHIP as I think it's a really good product, and I'd like to help users as well.

**Comment by wernight** [comment]
Bumb

**Comment by nyboer** [comment]
I appreciate your efforts, and have included other change suggestions. I closed the PR because I don't want to continue to expand the documentation with additional command-line options. It's simply an editorial choice.

**Comment by wernight** [comment]
OK thanks.

Would you consider suggesting `nmtui` instead of `nmcli` which would remove a large block of that documentation and make it easier for users to setup their Wi-Fi?

**Pull request closed without merging**
