### PR TITLE
Update _advanced-headless.md

### PR DESCRIPTION
**Pull request by wernight**
I really wish I knew about the serial console via USB from the beginning; it'd have helped quite a lot. This commit is:
- Making the structure clearer that an existing Wi-Fi (or ethernet) connection isn't required.
- Moving the serial console via USB more prominently as it's by far the easier method to get started with CHIP (and setting up WiFi) for people who have Linux (and  probably many more).
- Regrouping the USB-to-UART cable section tighter together as it should be really one thing.

### CODE REVIEW

**Comment by wernight** [comment]
Actually there is even another improvement I should add once this one is in. That's using a Chrome app like https://chrome.google.com/webstore/detail/beagle-term/gkdofhllgfohlddimiiildbgoggdpoea/ which works on nearly all platforms including Chromebooks. Tested, and it's one of the simplest and most cross platform solution to get started with CHIP.

**Comment by wernight** [comment]
Please give an update on the PR. I spent time to provide them in hope that it helps CHIP as I think it's a really good product, and I'd like to help users as well.

**Comment by nyboer** [comment]
Thanks for the ping. I'm going to incorporate your suggestions into some other edits.

**Comment by wernight** [comment]
I gave you edit access so you can edit this PR.

**Pull request closed without merging**
